project:
  type: "website"
  title: "PB4A7 - Quantitative Applications for Behavioural Science"
  output-dir: docs
  render:
    - "index.qmd"
    - "2024/*.qmd"
    - "2024/weeks/week00/*.qmd"
    - "2024/weeks/week01/*.qmd"
    - "2024/weeks/week02/*.qmd"
    - "2024/weeks/week03/*.qmd"
    - "2024/weeks/week04/*.qmd"
    - "2024/weeks/week05/*.qmd"
    - "2024/weeks/week06/*.qmd"
    - "2024/weeks/week07/*.qmd"
    - "2024/weeks/week08/*.qmd"
    - "2024/weeks/week09/*.qmd"
    - "2024/weeks/week10/*.qmd"
    - "2024/weeks/week11/*.qmd"
    - "2024/weeks/week12/*.qmd"
    
website:
  title: "PB4A7 - Quantitative Applications for Behavioural Science"
  page-navigation: true
  reader-mode: true
  open-graph: true
  twitter-card: 
    creator: "@georgemelios"
    site: "\\www.georgemelios.com"
  favicon: "figures/icons/course_favicon.png"
  search:
    location: navbar
    type: textbox
  sidebar:
    style: docked
    contents:
      - href: 2024/index.qmd
        text: "ğŸ  Home"
        style:
          margin-bottom: "10px"
      - href: 2024/syllabus.qmd
        text: "ğŸ““ Syllabus"
        style:
          margin-bottom: "10px"
      - href: 2024/Stata.qmd
        text: "STATA resources"
        style:
          margin-bottom: "10px"
      - href: 2024/R.qmd
        text: "R & Python resources"
        style:
          margin-bottom: "10px"
    # - href: 2024/assignments.qmd
      #   text: "âœï¸ Assignments"
      #   contents:
      #     - href: 2024/assignments/assignment01.qmd
      #       text: "ğŸ“ Assignment 01"
      #     - href: 2024/assignments/assignment02.qmd
      #       text: "ğŸ“ Assignment 02"
      #     - href: 2024/assignments/group_project.qmd
      #       text: "ğŸ‘¥ Group Project"
      - section: "ğŸ—“ï¸ Weeks"
        contents:
          - href: 2024/weeks/week00/page.qmd
            text: Presessionals
            contents:
              - href: 2024/weeks/week00/page.qmd
              
          - href: 2024/weeks/week01/page.qmd
            text: Week 01
            contents:
              - href: 2024/weeks/week01/page.qmd
                text: ğŸ‘¨â€ğŸ« Lecture Material
              - href: 2024/weeks/week01/page1.qmd
                text: ğŸ’» Seminar Material
          - href: 2024/weeks/week02/page.qmd
            text: Week 02
            contents:
              - href: 2024/weeks/week02/page.qmd
                text: ğŸ‘¨â€ğŸ« Lecture Material
              - href: 2024/weeks/week02/page1.qmd
                text: ğŸ’» Seminar Material
          - href: 2024/weeks/week03/page.qmd
            text: Week 03
            contents:
              - href: 2024/weeks/week03/page.qmd
                text: ğŸ‘¨â€ğŸ« Lecture Material
              - href: 2024/weeks/week03/page1.qmd
                text: ğŸ’» Seminar Material
          - href: 2024/weeks/week04/page.qmd
            text: Week 04
            contents:
              - href: 2024/weeks/week04/page.qmd
                text: ğŸ‘¨â€ğŸ« Lecture Material
              - href: 2024/weeks/week04/page1.qmd
                text: ğŸ’» Seminar Material
          - href: 2024/weeks/week05/page.qmd
            text: Week 05
            contents:
              - href: 2024/weeks/week05/page.qmd
                text: ğŸ‘¨â€ğŸ« Lecture Material
              - href: 2024/weeks/week05/page1.qmd
                text: ğŸ’» Seminar Material
          - href: 2024/weeks/week06/page.qmd
            text: Week 06
            contents:
              - href: 2024/weeks/week06/page.qmd
                text: ğŸ‘¨â€ğŸ« Lecture Material
              - href: 2024/weeks/week06/page1.qmd
                text: ğŸ’» Seminar Material
          - href: 2024/weeks/week07/page.qmd
            text: Week 07
            contents:
              - href: 2024/weeks/week07/page.qmd
                text: ğŸ‘¨â€ğŸ« Lecture Material
              - href: 2024/weeks/week07/page1.qmd
                text: ğŸ’» Seminar Material
          - href: 2024/weeks/week08/page.qmd
            text: Week 08
            contents:
              - href: 2024/weeks/week08/page.qmd
                text: ğŸ‘¨â€ğŸ« Lecture Material
              - href: 2024/weeks/week08/page1.qmd
                text: ğŸ’» Seminar Material
          - href: 2024/weeks/week09/page.qmd
            text: Week 09
            contents:
              - href: 2024/weeks/week09/page.qmd
                text: ğŸ‘¨â€ğŸ« Lecture Material
              - href: 2024/weeks/week09/page1.qmd
                text: ğŸ’» Seminar Material
          - href: 2024/weeks/week10/page.qmd
            text: Week 10
            contents:
              - href: 2024/weeks/week10/page.qmd
                text: ğŸ‘¨â€ğŸ« Lecture Material
              - href: 2024/weeks/week10/page1.qmd
                text: ğŸ’» Seminar Material
          - href: 2024/weeks/week11/page.qmd
            text: Week 11
            contents:
              - href: 2024/weeks/week12/page.qmd
                text: ğŸ‘¨â€ğŸ« Lecture Material
              - href: 2024/weeks/week11/page1.qmd
                text: ğŸ’» Seminar Material
          - href: 2024/weeks/week12/page.qmd
            text: Guest Lecture
            contents:
              - href: 2024/weeks/week12/page.qmd
                text: ğŸ‘¨â€ğŸ« Lecture Material


  navbar:
    background: primary
  page-footer:
    background: light
    left: "![](/figures/logos/MY_INSTITUTION.png)"
    right: "Copyright 2024, London School of Economics & Political Science" 



bibliography: references/references.bib
csl: references/chicago-author-date.csl


format:
  html:
    author: Dr. [George Melios](#)
    author-meta: Dr. George Melios
    date-format: "DD MMMM YYYY"

    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: ^(?:http:|https:)\/\/(?:lse-dsi\.github\.io\/|localhost)

    theme:
      light: 
        - journal
        - css/custom.scss # I use this just to change the default colour
    css: 
      - css/custom_style.css
      - css/syllabus.css
    toc: true


